apiVersion: v1
kind: Service
metadata:
  name: {{.AppName}}
  labels:
    app: {{.AppName}}
    apps: {{.AppName}}  
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.AppName}}
---    
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.AppName}}
  labels:
    app: {{.AppName}}
    apps: {{.AppName}}    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.AppName}}
  template:
    metadata:
      labels:
        app: {{.AppName}}
    spec:
      containers:
      - name: {{.AppName}}
        image: {{.Image}}
        ports:
        - containerPort: 80
