apiVersion: v1
kind: Service
metadata:
  name: {{.AppName}}
  labels:
    apps: {{.AppName}}  
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    apps: {{.AppName}}
---    
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.AppName}}
  labels:
    apps: {{.AppName}}    
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      apps: {{.AppName}}
  template:
    metadata:
      labels:
        apps: {{.AppName}}
    spec:
      containers:
      - name: {{.AppName}}
        image: {{.Image}}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: {{.LimitCpu}}
            memory: {{.LimitMemory}}
          requests:
            cpu: {{.RequestCpu}}
            memory: {{.RequestMemory}} 
